/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DummyInterface extends Interface {
  getFunction(nameOrSignature: "addCount" | "getCount"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Inc"): EventFragment;

  encodeFunctionData(functionFragment: "addCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "getCount", values?: undefined): string;

  decodeFunctionResult(functionFragment: "addCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getCount", data: BytesLike): Result;
}

export namespace IncEvent {
  export type InputTuple = [caller: AddressLike, newCount: BigNumberish];
  export type OutputTuple = [caller: string, newCount: bigint];
  export interface OutputObject {
    caller: string;
    newCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Dummy extends BaseContract {
  connect(runner?: ContractRunner | null): Dummy;
  waitForDeployment(): Promise<this>;

  interface: DummyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addCount: TypedContractMethod<[], [void], "nonpayable">;

  getCount: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addCount"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCount"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "Inc"
  ): TypedContractEvent<
    IncEvent.InputTuple,
    IncEvent.OutputTuple,
    IncEvent.OutputObject
  >;

  filters: {
    "Inc(address,uint256)": TypedContractEvent<
      IncEvent.InputTuple,
      IncEvent.OutputTuple,
      IncEvent.OutputObject
    >;
    Inc: TypedContractEvent<
      IncEvent.InputTuple,
      IncEvent.OutputTuple,
      IncEvent.OutputObject
    >;
  };
}
